osx_image: xcode7.3
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler
  - cocoapods

install:
  - bundle install
  - cd Demo ; bundle exec pod install

script: rake test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
