version: 2
jobs:
  build:
    xcode:
      version: 9.0
    environment:
      LANG: en_US.UTF-8

dependencies:
  pre:
    - scripts/check-trivial-changes.sh && circleci step halt || true # only continue if there are non-trivial changes
    - curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
  override:
    - brew update ; brew update # Due to a problem with Homebrew, see: https://github.com/Homebrew/brew/issues/991
    - brew install swiftlint
    - bundle install
    - scripts/bootstrap-if-needed.sh # only bootstrap if we have updated dependencies since our last cache.
    - cd Demo ; bundle exec pod repo update
    - cd Demo ; bundle exec pod install --verbose # Verbose to keep CI alive during long Specs repo setups.
  cache_directories:
    - "Carthage" # Cache carthage to speed up builds.

test:
  override:
    - rake test && rake test:carthage && rake build_demo
  post:
    - bundle exec danger
    - bash <(curl -s https://codecov.io/bash) -J Moya
